# Generated by Django 5.0.3 on 2024-03-24 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('instrumentType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('releaseDate', models.DateField()),
                ('rating', models.FloatField()),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.musician')),
            ],
        ),
    ]
